### ISSUE TITLE
Need help :)

### ISSUE THREAD

**Issue by hassank185** [tcmhoang/tcmhoang.github.io#1]
Hi Conrad Hoang! sorry for making this issue but there's no way to contact you so i thought this is the best way to make the issue.

I need some help in the auto_router guards you help the guy with auto gurard and bloc . Iam having the same but the conversation is not helpful to me on that issue can you please contact  me or if there's a proper email or linkedIn account i can discuss the issue with you. Hoping for fast reply :)
Thanks

**Comment by tcmhoang** [comment]
I've already responded to your original issue. If you have any further questions, please ask them on the original thread. I'm closing this issue for now.
